{% set name = "django-upgrade" %}
{% set version = "1.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e65021029e7d18b407bd128a8ccb31e5e06685068b37b6b1eaf2f77aa3d3df98

build:
  number: 0
  noarch: python
  entry_points:
    - django-upgrade = django_upgrade.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - tokenize-rt >=4.1

test:
  imports:
    - django_upgrade
  commands:
    - pip check
    - django-upgrade --help
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-upgrade
  summary: Automatically upgrade your Django projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
