{% set name = "django-upgrade" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-upgrade-{{ version }}.tar.gz
  sha256: 6f1a875e3e24dd9cc93dec4b1881b70b89782e2b3da7b7c596dd31e684b89abf

build:
  number: 0
  noarch: python
  entry_points:
    - django-upgrade = django_upgrade.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=40.6.0
  run:
    - python >=3.8
    - tokenize-rt >=4.1.0

test:
  imports:
    - django_upgrade
    - django_upgrade.fixers
  commands:
    - pip check
    - django-upgrade --help
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-upgrade
  summary: Automatically upgrade your Django projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
