{% set name = "django-upgrade" %}
{% set version = "1.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4054a225e12a768347790cfbeb9ea141c71fe5c74b29a8ccd5ea3fd97c8fa705

build:
  number: 0
  noarch: python
  entry_points:
    - django-upgrade = django_upgrade.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=40.6.0
  run:
    - python >=3.8
    - tokenize-rt >=4.1.0

test:
  imports:
    - django_upgrade
    - django_upgrade.fixers
  commands:
    - pip check
    - django-upgrade --help
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-upgrade
  summary: Automatically upgrade your Django projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
